---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fbdeploy
  labels:
    app: facebook
spec:
  selector:
    matchLabels:
      app: facebook 
  replicas: 2 
  template:
    metadata:
      name: fbpod
      labels:
        app: facebook
    spec:
      containers:
        - name: fbcont
          image: mohammadkarishma517/karishma-batch14:pythonapp

          ports:
            - containerPort: 8080

